import sqlite3
import json
import pandas as pd
from pathlib import Path

# Absolute imports based on the new modular architecture
from src.core.config import (
    TABLE_ERP,
    TABLE_GATEWAY,
    TABLE_BANK,
    TABLE_ERP_GW_TRUE,
    TABLE_GW_BANK_TRUE,
    TABLE_ERP_GW_PRED,
    TABLE_GW_BANK_PRED,
    GROUND_TRUTH_ERP_GW_PATH,
    GROUND_TRUTH_GW_BANK_PATH,
)

def get_connection(db_path: Path) -> sqlite3.Connection:
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    return conn


def ensure_matching_stage_column(conn: sqlite3.Connection, table_name: str):
    """Adds the stage column to older SQLite DBs created before the schema revision."""
    columns = conn.execute(f"PRAGMA table_info({table_name})").fetchall()
    if any(col[1] == "matching_stage" for col in columns):
        return
    conn.execute(f"ALTER TABLE {table_name} ADD COLUMN matching_stage TEXT NOT NULL DEFAULT 'Unknown'")


def init_database(db_path: Path):
    db_path.parent.mkdir(parents=True, exist_ok=True)
    conn = get_connection(db_path)
    cursor = conn.cursor()

    # 1. Raw Data Tables
    cursor.execute(f"""
        CREATE TABLE IF NOT EXISTS {TABLE_ERP} (
            erp_entry_id TEXT PRIMARY KEY,
            customer_account_id TEXT,
            invoice_number TEXT,
            gross_amount REAL,
            tds_expected REAL,
            currency TEXT,
            entry_date TEXT,
            status TEXT,
            allocation_key TEXT
        )
    """)

    cursor.execute(f"""
        CREATE TABLE IF NOT EXISTS {TABLE_GATEWAY} (
            payment_id TEXT PRIMARY KEY,
            settlement_id TEXT,
            gateway_status TEXT,
            gross_amount REAL,
            fee_deducted REAL,
            tax_on_fee REAL,
            net_settled REAL,
            amount_reversed REAL,
            settled_at TEXT,
            bank_utr TEXT,
            invoices TEXT
        )
    """)

    cursor.execute(f"""
        CREATE TABLE IF NOT EXISTS {TABLE_BANK} (
            bank_entry_id TEXT PRIMARY KEY,
            value_date TEXT,
            transaction_type TEXT,
            credit_amount REAL,
            debit_amount REAL,
            running_balance REAL,
            remittance_info TEXT,
            reversal_indicator BOOLEAN
        )
    """)

    # 2. Ground Truth Edge Tables (Loaded from CSV)
    cursor.execute(f"""
        CREATE TABLE IF NOT EXISTS {TABLE_ERP_GW_TRUE} (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            erp_id TEXT NOT NULL,
            gw_id TEXT NOT NULL,
            erp_gw_amount REAL NOT NULL
        )
    """)

    cursor.execute(f"""
        CREATE TABLE IF NOT EXISTS {TABLE_GW_BANK_TRUE} (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            gw_id TEXT NOT NULL,
            bank_id TEXT NOT NULL,
            gw_bank_amount REAL NOT NULL
        )
    """)

    # 3. Predicted Result Edge Tables (Generated by Matcher Engine)
    cursor.execute(f"""
        CREATE TABLE IF NOT EXISTS {TABLE_ERP_GW_PRED} (
            edge_id INTEGER PRIMARY KEY AUTOINCREMENT,
            erp_order_id TEXT NOT NULL,
            gateway_payment_id TEXT NOT NULL,
            allocated_amount REAL NOT NULL,
            match_type TEXT NOT NULL,
            matching_stage TEXT NOT NULL DEFAULT 'Unknown',
            confidence_score REAL NOT NULL,
            notes TEXT
        )
    """)

    cursor.execute(f"""
        CREATE TABLE IF NOT EXISTS {TABLE_GW_BANK_PRED} (
            edge_id INTEGER PRIMARY KEY AUTOINCREMENT,
            gateway_payment_id TEXT NOT NULL,
            bank_entry_id TEXT NOT NULL,
            allocated_amount REAL NOT NULL,
            match_type TEXT NOT NULL,
            matching_stage TEXT NOT NULL DEFAULT 'Unknown',
            confidence_score REAL NOT NULL,
            notes TEXT
        )
    """)

    ensure_matching_stage_column(conn, TABLE_ERP_GW_PRED)
    ensure_matching_stage_column(conn, TABLE_GW_BANK_PRED)

    conn.commit()
    conn.close()


def ingest_data(erp_path: Path, gateway_path: Path, bank_path: Path, db_path: Path) -> dict:
    conn = get_connection(db_path)
    counts = {}

    # Ingest ERP
    if erp_path.exists():
        with open(erp_path, "r", encoding="utf-8") as f:
            erp_data = json.load(f)
        df_erp = pd.DataFrame(erp_data)
        df_erp.to_sql(TABLE_ERP, conn, if_exists="replace", index=False)
        counts[TABLE_ERP] = len(df_erp)

    # Ingest Gateway
    if gateway_path.exists():
        with open(gateway_path, "r", encoding="utf-8") as f:
            gw_data = json.load(f)
        for row in gw_data:
            if "invoices" in row and isinstance(row["invoices"], list):
                row["invoices"] = json.dumps(row["invoices"])
        df_gw = pd.DataFrame(gw_data)
        df_gw.to_sql(TABLE_GATEWAY, conn, if_exists="replace", index=False)
        counts[TABLE_GATEWAY] = len(df_gw)

    # Ingest Bank
    if bank_path.exists():
        df_bank = pd.read_csv(bank_path)
        df_bank.to_sql(TABLE_BANK, conn, if_exists="replace", index=False)
        counts[TABLE_BANK] = len(df_bank)

    # Ingest Separate Ground Truth Edge Tables
    if GROUND_TRUTH_ERP_GW_PATH.exists():
        df_eg_true = pd.read_csv(GROUND_TRUTH_ERP_GW_PATH)
        df_eg_true.to_sql(TABLE_ERP_GW_TRUE, conn, if_exists="replace", index=False)
        counts[TABLE_ERP_GW_TRUE] = len(df_eg_true)

    if GROUND_TRUTH_GW_BANK_PATH.exists():
        df_gb_true = pd.read_csv(GROUND_TRUTH_GW_BANK_PATH)
        df_gb_true.to_sql(TABLE_GW_BANK_TRUE, conn, if_exists="replace", index=False)
        counts[TABLE_GW_BANK_TRUE] = len(df_gb_true)

    conn.commit()
    conn.close()
    return counts


# ==========================================
# DATA ACCESS LAYER (DAL)
# ==========================================

def fetch_table_df(table_name: str, db_path: Path) -> pd.DataFrame:
    """Fetch an entire table as a Pandas DataFrame."""
    conn = get_connection(db_path)
    try:
        return pd.read_sql_query(f"SELECT * FROM {table_name}", conn)
    finally:
        conn.close()

def fetch_edges_df(edge_table: str, db_path: Path) -> pd.DataFrame:
    """Fetch a graph edge table as a Pandas DataFrame."""
    conn = get_connection(db_path)
    try:
        return pd.read_sql_query(f"SELECT * FROM {edge_table}", conn)
    finally:
        conn.close()

def clear_graph_edges(db_path: Path):
    """Truncate the predicted edge tables before a new matching run."""
    conn = get_connection(db_path)
    try:
        ensure_matching_stage_column(conn, TABLE_ERP_GW_PRED)
        ensure_matching_stage_column(conn, TABLE_GW_BANK_PRED)

        cursor = conn.cursor()
        cursor.execute("DELETE FROM erp_gw_pred;")
        cursor.execute("DELETE FROM sqlite_sequence WHERE name = 'erp_gw_pred';")
        cursor.execute("DELETE FROM gw_bank_pred;")
        cursor.execute("DELETE FROM sqlite_sequence WHERE name = 'gw_bank_pred';")
        conn.commit()
    finally:
        conn.close()


def save_graph_edges(erp_gw_edges: list, gw_bank_edges: list, db_path: Path):
    """Insert newly computed graph edges into the predicted result tables."""
    if not erp_gw_edges and not gw_bank_edges:
        return

    conn = get_connection(db_path)
    try:
        ensure_matching_stage_column(conn, TABLE_ERP_GW_PRED)
        ensure_matching_stage_column(conn, TABLE_GW_BANK_PRED)

        cursor = conn.cursor()
        cursor.execute("PRAGMA synchronous = NORMAL;")
        cursor.execute("PRAGMA journal_mode = WAL;")

        if erp_gw_edges:
            erp_params = [
                (
                    e["erp_order_id"], e["gateway_payment_id"],
                    float(e["allocated_amount"]), e["match_type"],
                    e.get("matching_stage", "Unknown"),
                    float(e["confidence_score"]), e.get("notes", "")
                )
                for e in erp_gw_edges
            ]
            cursor.executemany("""
                INSERT INTO erp_gw_pred
                (erp_order_id, gateway_payment_id, allocated_amount, match_type, matching_stage, confidence_score, notes)
                VALUES (?, ?, ?, ?, ?, ?, ?)
            """, erp_params)

        if gw_bank_edges:
            gw_params = [
                (
                    e["gateway_payment_id"], e["bank_entry_id"],
                    float(e["allocated_amount"]), e["match_type"],
                    e.get("matching_stage", "Unknown"),
                    float(e["confidence_score"]), e.get("notes", "")
                )
                for e in gw_bank_edges
            ]
            cursor.executemany("""
                INSERT INTO gw_bank_pred
                (gateway_payment_id, bank_entry_id, allocated_amount, match_type, matching_stage, confidence_score, notes)
                VALUES (?, ?, ?, ?, ?, ?, ?)
            """, gw_params)

        conn.commit()
    finally:
        conn.close()

initialize_database_schema = init_database
